server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: cliente-service

  # ── JPA / Hibernate ───────────────────────────────────────────────
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
